# Generated by Django 3.1.7 on 2021-03-30 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quali', models.CharField(max_length=30)),
                ('special', models.CharField(max_length=30)),
                ('insti', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('board', models.CharField(max_length=30)),
                ('grades', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=80)),
                ('job_comp', models.CharField(max_length=100)),
                ('job_descp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('dp', models.ImageField(upload_to='pics')),
                ('birth', models.DateField()),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('add', models.CharField(max_length=100)),
                ('descp', models.TextField()),
                ('hobbies', models.TextField()),
                ('lang', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proj_name', models.CharField(max_length=100)),
                ('proj_descp', models.TextField()),
                ('proj_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=50)),
                ('skill_rate', models.IntegerField()),
            ],
        ),
    ]
