# Generated by Django 3.1.7 on 2021-03-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_auto_20210330_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra_curri',
            name='curri_year',
            field=models.IntegerField(),
        ),
    ]
